apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:alpine
        env:
        - name: INFLUXDB_DB
          value: "kube-metrics"
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_USER
          value: "telegraf"
        - name: INFLUXDB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-passwords
              key: telegraf
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf/
      volumes:
      - name: config
        configMap:
          name: telegraf-config
          items:
          - key: config
            path: telegraf.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    tier: backend
data:
  config : |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = true
    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.netstat]]
    [[inputs.net]]